/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umb.junctionbox;

class junctionboxJNI {
  public final static native long new_doubleArray(int jarg1);
  public final static native void delete_doubleArray(long jarg1);
  public final static native double doubleArray_getitem(long jarg1, int jarg2);
  public final static native void doubleArray_setitem(long jarg1, int jarg2, double jarg3);
  public final static native int List_Length(long jarg1);
  public final static native long jballoc(long jarg1);
  public final static native void jbfree(long jarg1);
  public final static native long List_Create();
  public final static native void List_Destroy(long jarg1);
  public final static native void List_Append(long jarg1, long jarg2);
  public final static native long BuildSimpleBNet();
  public final static native long BNet_StateSpaceWeightedElimOrdering(long jarg1);
  public final static native long Variable_CreateDiscrete(String jarg1, int jarg2, long jarg3);
  public final static native long VariableOrdering_Create(long jarg1);
  public final static native long VariableSet_Create(long jarg1);
  public final static native void VariableSet_Add(long jarg1, long jarg2);
  public final static native long Pot_CreateTabular(String jarg1, long jarg2, long jarg3);
  public final static native long CPT_Create_ParentList(long jarg1, long jarg2, long jarg3);
  public final static native long Observation_Create(long jarg1, int jarg2);
  public final static native void BNet_InitializePotentials(long jarg1);
  public final static native void BNet_BuildElimTree(long jarg1, long jarg2);
  public final static native void BNet_CollectEvidence(long jarg1);
  public final static native void BNet_DistributeEvidence(long jarg1);
  public final static native long BNet_AllContClqPot(long jarg1, long jarg2);
  public final static native long Pot_SumMarginTabularSingleVbl(long jarg1, long jarg2);
  public final static native long VariableSet_ComputeMargInd(long jarg1, long jarg2);
  public final static native void BNet_ComputeSumMarginals(long jarg1);
  public final static native long BNet_Create_List(long jarg1, long jarg2);
  public final static native long BNet_Create_List2(long jarg1, long jarg2, long jarg3);
  public final static native void BNet_InitializePotentialsLog(long jarg1);
  public final static native void BNet_CollectEvidenceLog(long jarg1);
  public final static native void BNet_DistributeEvidenceLog(long jarg1);
  public final static native long BuildSimpleBNetDObsLog(int jarg1);
  public final static native void Print_BNetLog(long jarg1);
  public final static native String Pot_ToStringLog(long jarg1);
  public final static native long Observation_CreateLog(long jarg1, int jarg2);
  public final static native long Pot_CreateTabularUnityLog(String jarg1, long jarg2);
  public final static native long Pot_ProductTabularLog(long jarg1, long jarg2, long jarg3);
  public final static native long Pot_UpdateRatioTabularLog(long jarg1, long jarg2);
  public final static native long Pot_SumMarginTabularLog(long jarg1, long jarg2);
  public final static native long Pot_SumMarginTabularSingleVblLog(long jarg1, long jarg2);
  public final static native void Print_BNet(long jarg1);
}
