/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umb.junctionbox;

public class junctionbox {
  public static SWIGTYPE_p_double new_doubleArray(int nelements) {
    long cPtr = junctionboxJNI.new_doubleArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void delete_doubleArray(SWIGTYPE_p_double ary) {
    junctionboxJNI.delete_doubleArray(SWIGTYPE_p_double.getCPtr(ary));
  }

  public static double doubleArray_getitem(SWIGTYPE_p_double ary, int index) {
    return junctionboxJNI.doubleArray_getitem(SWIGTYPE_p_double.getCPtr(ary), index);
  }

  public static void doubleArray_setitem(SWIGTYPE_p_double ary, int index, double value) {
    junctionboxJNI.doubleArray_setitem(SWIGTYPE_p_double.getCPtr(ary), index, value);
  }

  public static int List_Length(SWIGTYPE_p_List l) {
    return junctionboxJNI.List_Length(SWIGTYPE_p_List.getCPtr(l));
  }

  public static SWIGTYPE_p_void jballoc(long amt) {
    long cPtr = junctionboxJNI.jballoc(amt);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void jbfree(SWIGTYPE_p_void p) {
    junctionboxJNI.jbfree(SWIGTYPE_p_void.getCPtr(p));
  }

  public static SWIGTYPE_p_List List_Create() {
    long cPtr = junctionboxJNI.List_Create();
    return (cPtr == 0) ? null : new SWIGTYPE_p_List(cPtr, false);
  }

  public static void List_Destroy(SWIGTYPE_p_List arg0) {
    junctionboxJNI.List_Destroy(SWIGTYPE_p_List.getCPtr(arg0));
  }

  public static void List_Append(SWIGTYPE_p_List l, SWIGTYPE_p_void contents) {
    junctionboxJNI.List_Append(SWIGTYPE_p_List.getCPtr(l), SWIGTYPE_p_void.getCPtr(contents));
  }

  public static SWIGTYPE_p_BNet BuildSimpleBNet() {
    long cPtr = junctionboxJNI.BuildSimpleBNet();
    return (cPtr == 0) ? null : new SWIGTYPE_p_BNet(cPtr, false);
  }

  public static SWIGTYPE_p_VertexOrdering BNet_StateSpaceWeightedElimOrdering(SWIGTYPE_p_BNet arg0) {
    long cPtr = junctionboxJNI.BNet_StateSpaceWeightedElimOrdering(SWIGTYPE_p_BNet.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_VertexOrdering(cPtr, false);
  }

  public static SWIGTYPE_p_Variable Variable_CreateDiscrete(String label, int cardinality, SWIGTYPE_p_double valueData) {
    long cPtr = junctionboxJNI.Variable_CreateDiscrete(label, cardinality, SWIGTYPE_p_double.getCPtr(valueData));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Variable(cPtr, false);
  }

  public static SWIGTYPE_p_VariableOrdering VariableOrdering_Create(SWIGTYPE_p_List l) {
    long cPtr = junctionboxJNI.VariableOrdering_Create(SWIGTYPE_p_List.getCPtr(l));
    return (cPtr == 0) ? null : new SWIGTYPE_p_VariableOrdering(cPtr, false);
  }

  public static SWIGTYPE_p_VariableSet VariableSet_Create(SWIGTYPE_p_VariableOrdering o) {
    long cPtr = junctionboxJNI.VariableSet_Create(SWIGTYPE_p_VariableOrdering.getCPtr(o));
    return (cPtr == 0) ? null : new SWIGTYPE_p_VariableSet(cPtr, false);
  }

  public static void VariableSet_Add(SWIGTYPE_p_VariableSet arg0, SWIGTYPE_p_Variable v) {
    junctionboxJNI.VariableSet_Add(SWIGTYPE_p_VariableSet.getCPtr(arg0), SWIGTYPE_p_Variable.getCPtr(v));
  }

  public static SWIGTYPE_p_Pot Pot_CreateTabular(String label, SWIGTYPE_p_VariableSet vbls, SWIGTYPE_p_double valueData) {
    long cPtr = junctionboxJNI.Pot_CreateTabular(label, SWIGTYPE_p_VariableSet.getCPtr(vbls), SWIGTYPE_p_double.getCPtr(valueData));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Pot(cPtr, false);
  }

  public static SWIGTYPE_p_CPT CPT_Create_ParentList(SWIGTYPE_p_List parents, SWIGTYPE_p_Variable tableFor, SWIGTYPE_p_Pot pot) {
    long cPtr = junctionboxJNI.CPT_Create_ParentList(SWIGTYPE_p_List.getCPtr(parents), SWIGTYPE_p_Variable.getCPtr(tableFor), SWIGTYPE_p_Pot.getCPtr(pot));
    return (cPtr == 0) ? null : new SWIGTYPE_p_CPT(cPtr, false);
  }

  public static SWIGTYPE_p_Observation Observation_Create(SWIGTYPE_p_VariableSet v, int value) {
    long cPtr = junctionboxJNI.Observation_Create(SWIGTYPE_p_VariableSet.getCPtr(v), value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Observation(cPtr, false);
  }

  public static void BNet_InitializePotentials(SWIGTYPE_p_BNet arg0) {
    junctionboxJNI.BNet_InitializePotentials(SWIGTYPE_p_BNet.getCPtr(arg0));
  }

  public static void BNet_BuildElimTree(SWIGTYPE_p_BNet arg0, SWIGTYPE_p_VertexOrdering o) {
    junctionboxJNI.BNet_BuildElimTree(SWIGTYPE_p_BNet.getCPtr(arg0), SWIGTYPE_p_VertexOrdering.getCPtr(o));
  }

  public static void BNet_CollectEvidence(SWIGTYPE_p_BNet arg0) {
    junctionboxJNI.BNet_CollectEvidence(SWIGTYPE_p_BNet.getCPtr(arg0));
  }

  public static void BNet_DistributeEvidence(SWIGTYPE_p_BNet arg0) {
    junctionboxJNI.BNet_DistributeEvidence(SWIGTYPE_p_BNet.getCPtr(arg0));
  }

  public static SWIGTYPE_p_List BNet_AllContClqPot(SWIGTYPE_p_BNet arg0, SWIGTYPE_p_Variable vbl) {
    long cPtr = junctionboxJNI.BNet_AllContClqPot(SWIGTYPE_p_BNet.getCPtr(arg0), SWIGTYPE_p_Variable.getCPtr(vbl));
    return (cPtr == 0) ? null : new SWIGTYPE_p_List(cPtr, false);
  }

  public static SWIGTYPE_p_double Pot_SumMarginTabularSingleVbl(SWIGTYPE_p_Pot p, SWIGTYPE_p_Variable v) {
    long cPtr = junctionboxJNI.Pot_SumMarginTabularSingleVbl(SWIGTYPE_p_Pot.getCPtr(p), SWIGTYPE_p_Variable.getCPtr(v));
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_MulInd VariableSet_ComputeMargInd(SWIGTYPE_p_VariableSet arg0, SWIGTYPE_p_VariableSet target) {
    long cPtr = junctionboxJNI.VariableSet_ComputeMargInd(SWIGTYPE_p_VariableSet.getCPtr(arg0), SWIGTYPE_p_VariableSet.getCPtr(target));
    return (cPtr == 0) ? null : new SWIGTYPE_p_MulInd(cPtr, false);
  }

  public static void BNet_ComputeSumMarginals(SWIGTYPE_p_BNet arg0) {
    junctionboxJNI.BNet_ComputeSumMarginals(SWIGTYPE_p_BNet.getCPtr(arg0));
  }

  public static SWIGTYPE_p_BNet BNet_Create_List(SWIGTYPE_p_VariableOrdering vbls, SWIGTYPE_p_List tables) {
    long cPtr = junctionboxJNI.BNet_Create_List(SWIGTYPE_p_VariableOrdering.getCPtr(vbls), SWIGTYPE_p_List.getCPtr(tables));
    return (cPtr == 0) ? null : new SWIGTYPE_p_BNet(cPtr, false);
  }

  public static SWIGTYPE_p_BNet BNet_Create_List2(SWIGTYPE_p_VariableOrdering vbls, SWIGTYPE_p_List tables, SWIGTYPE_p_List obs) {
    long cPtr = junctionboxJNI.BNet_Create_List2(SWIGTYPE_p_VariableOrdering.getCPtr(vbls), SWIGTYPE_p_List.getCPtr(tables), SWIGTYPE_p_List.getCPtr(obs));
    return (cPtr == 0) ? null : new SWIGTYPE_p_BNet(cPtr, false);
  }

  public static void BNet_InitializePotentialsLog(SWIGTYPE_p_BNet arg0) {
    junctionboxJNI.BNet_InitializePotentialsLog(SWIGTYPE_p_BNet.getCPtr(arg0));
  }

  public static void BNet_CollectEvidenceLog(SWIGTYPE_p_BNet arg0) {
    junctionboxJNI.BNet_CollectEvidenceLog(SWIGTYPE_p_BNet.getCPtr(arg0));
  }

  public static void BNet_DistributeEvidenceLog(SWIGTYPE_p_BNet arg0) {
    junctionboxJNI.BNet_DistributeEvidenceLog(SWIGTYPE_p_BNet.getCPtr(arg0));
  }

  public static SWIGTYPE_p_BNet BuildSimpleBNetDObsLog(int val) {
    long cPtr = junctionboxJNI.BuildSimpleBNetDObsLog(val);
    return (cPtr == 0) ? null : new SWIGTYPE_p_BNet(cPtr, false);
  }

  public static void Print_BNetLog(SWIGTYPE_p_BNet bn) {
    junctionboxJNI.Print_BNetLog(SWIGTYPE_p_BNet.getCPtr(bn));
  }

  public static String Pot_ToStringLog(SWIGTYPE_p_Pot arg0) {
    return junctionboxJNI.Pot_ToStringLog(SWIGTYPE_p_Pot.getCPtr(arg0));
  }

  public static SWIGTYPE_p_Observation Observation_CreateLog(SWIGTYPE_p_VariableSet v, int value) {
    long cPtr = junctionboxJNI.Observation_CreateLog(SWIGTYPE_p_VariableSet.getCPtr(v), value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Observation(cPtr, false);
  }

  public static SWIGTYPE_p_Pot Pot_CreateTabularUnityLog(String label, SWIGTYPE_p_VariableSet vbls) {
    long cPtr = junctionboxJNI.Pot_CreateTabularUnityLog(label, SWIGTYPE_p_VariableSet.getCPtr(vbls));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Pot(cPtr, false);
  }

  public static SWIGTYPE_p_Pot Pot_ProductTabularLog(SWIGTYPE_p_Pot p, SWIGTYPE_p_Pot q, SWIGTYPE_p_MulInd mi) {
    long cPtr = junctionboxJNI.Pot_ProductTabularLog(SWIGTYPE_p_Pot.getCPtr(p), SWIGTYPE_p_Pot.getCPtr(q), SWIGTYPE_p_MulInd.getCPtr(mi));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Pot(cPtr, false);
  }

  public static SWIGTYPE_p_Pot Pot_UpdateRatioTabularLog(SWIGTYPE_p_Pot newSep, SWIGTYPE_p_Pot oldSep) {
    long cPtr = junctionboxJNI.Pot_UpdateRatioTabularLog(SWIGTYPE_p_Pot.getCPtr(newSep), SWIGTYPE_p_Pot.getCPtr(oldSep));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Pot(cPtr, false);
  }

  public static SWIGTYPE_p_Pot Pot_SumMarginTabularLog(SWIGTYPE_p_Pot p, SWIGTYPE_p_MulInd m) {
    long cPtr = junctionboxJNI.Pot_SumMarginTabularLog(SWIGTYPE_p_Pot.getCPtr(p), SWIGTYPE_p_MulInd.getCPtr(m));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Pot(cPtr, false);
  }

  public static SWIGTYPE_p_Pot Pot_SumMarginTabularSingleVblLog(SWIGTYPE_p_Pot p, SWIGTYPE_p_Variable v) {
    long cPtr = junctionboxJNI.Pot_SumMarginTabularSingleVblLog(SWIGTYPE_p_Pot.getCPtr(p), SWIGTYPE_p_Variable.getCPtr(v));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Pot(cPtr, false);
  }

  public static void Print_BNet(SWIGTYPE_p_BNet bn) {
    junctionboxJNI.Print_BNet(SWIGTYPE_p_BNet.getCPtr(bn));
  }

}
