/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umb.junctionbox;

public class SWIGTYPE_p_Variable extends SWIG {
  private long swigCPtr;

  protected SWIGTYPE_p_Variable(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_Variable() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_Variable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected long getPointer() {
    return swigCPtr;
  }
}

