/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTELC__)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


static double *new_doubleArray(int nelements) { 
  return (double *) calloc(nelements,sizeof(double)); 
}

static void delete_doubleArray(double *ary) { 
  free(ary); 
}

static double doubleArray_getitem(double *ary, int index) {
    return ary[index];
}
static void doubleArray_setitem(double *ary, int index, double value) {
    ary[index] = value;
}


	#include"JB_Inference.h"
	int List_Length(List *l){
	    return l->size;
	}	


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_new_1doubleArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  double *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (double *)new_doubleArray(arg1);
  *(double **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_delete_1doubleArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  double *arg1 = (double *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  delete_doubleArray(arg1);
}


SWIGEXPORT jdouble JNICALL Java_edu_umb_junctionbox_junctionboxJNI_doubleArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jdouble jresult = 0 ;
  double *arg1 = (double *) 0 ;
  int arg2 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (double)doubleArray_getitem(arg1,arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_doubleArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jdouble jarg3) {
  double *arg1 = (double *) 0 ;
  int arg2 ;
  double arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (double)jarg3; 
  doubleArray_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jint JNICALL Java_edu_umb_junctionbox_junctionboxJNI_List_1Length(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  List *arg1 = (List *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(List **)&jarg1; 
  result = (int)List_Length(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_jballoc(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  size_t arg1 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  result = (void *)jballoc(arg1);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_jbfree(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  void *arg1 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  jbfree(arg1);
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_List_1Create(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  List *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (List *)List_Create();
  *(List **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_List_1Destroy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  List *arg1 = (List *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(List **)&jarg1; 
  List_Destroy(arg1);
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_List_1Append(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  List *arg1 = (List *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(List **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  List_Append(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BuildSimpleBNet(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  BNet *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (BNet *)BuildSimpleBNet();
  *(BNet **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BNet_1StateSpaceWeightedElimOrdering(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  BNet *arg1 = (BNet *) 0 ;
  VertexOrdering *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BNet **)&jarg1; 
  result = (VertexOrdering *)BNet_StateSpaceWeightedElimOrdering(arg1);
  *(VertexOrdering **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Variable_1CreateDiscrete(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int arg2 ;
  double *arg3 = (double *) 0 ;
  Variable *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (int)jarg2; 
  arg3 = *(double **)&jarg3; 
  result = (Variable *)Variable_CreateDiscrete(arg1,arg2,arg3);
  *(Variable **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_VariableOrdering_1Create(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  List *arg1 = (List *) 0 ;
  VariableOrdering *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(List **)&jarg1; 
  result = (VariableOrdering *)VariableOrdering_Create(arg1);
  *(VariableOrdering **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_VariableSet_1Create(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  VariableOrdering *arg1 = (VariableOrdering *) 0 ;
  VariableSet *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VariableOrdering **)&jarg1; 
  result = (VariableSet *)VariableSet_Create(arg1);
  *(VariableSet **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_VariableSet_1Add(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  VariableSet *arg1 = (VariableSet *) 0 ;
  Variable *arg2 = (Variable *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VariableSet **)&jarg1; 
  arg2 = *(Variable **)&jarg2; 
  VariableSet_Add(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Pot_1CreateTabular(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  VariableSet *arg2 = (VariableSet *) 0 ;
  double *arg3 = (double *) 0 ;
  Pot *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(VariableSet **)&jarg2; 
  arg3 = *(double **)&jarg3; 
  result = (Pot *)Pot_CreateTabular(arg1,arg2,arg3);
  *(Pot **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_CPT_1Create_1ParentList(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  List *arg1 = (List *) 0 ;
  Variable *arg2 = (Variable *) 0 ;
  Pot *arg3 = (Pot *) 0 ;
  CPT *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(List **)&jarg1; 
  arg2 = *(Variable **)&jarg2; 
  arg3 = *(Pot **)&jarg3; 
  result = (CPT *)CPT_Create_ParentList(arg1,arg2,arg3);
  *(CPT **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Observation_1Create(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  VariableSet *arg1 = (VariableSet *) 0 ;
  int arg2 ;
  Observation *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VariableSet **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (Observation *)Observation_Create(arg1,arg2);
  *(Observation **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BNet_1InitializePotentials(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  BNet *arg1 = (BNet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BNet **)&jarg1; 
  BNet_InitializePotentials(arg1);
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BNet_1BuildElimTree(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  BNet *arg1 = (BNet *) 0 ;
  VertexOrdering *arg2 = (VertexOrdering *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BNet **)&jarg1; 
  arg2 = *(VertexOrdering **)&jarg2; 
  BNet_BuildElimTree(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BNet_1CollectEvidence(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  BNet *arg1 = (BNet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BNet **)&jarg1; 
  BNet_CollectEvidence(arg1);
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BNet_1DistributeEvidence(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  BNet *arg1 = (BNet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BNet **)&jarg1; 
  BNet_DistributeEvidence(arg1);
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BNet_1AllContClqPot(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  BNet *arg1 = (BNet *) 0 ;
  Variable *arg2 = (Variable *) 0 ;
  List *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BNet **)&jarg1; 
  arg2 = *(Variable **)&jarg2; 
  result = (List *)BNet_AllContClqPot(arg1,arg2);
  *(List **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Pot_1SumMarginTabularSingleVbl(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  Pot *arg1 = (Pot *) 0 ;
  Variable *arg2 = (Variable *) 0 ;
  double *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Pot **)&jarg1; 
  arg2 = *(Variable **)&jarg2; 
  result = (double *)Pot_SumMarginTabularSingleVbl(arg1,arg2);
  *(double **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_VariableSet_1ComputeMargInd(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  VariableSet *arg1 = (VariableSet *) 0 ;
  VariableSet *arg2 = (VariableSet *) 0 ;
  MulInd *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VariableSet **)&jarg1; 
  arg2 = *(VariableSet **)&jarg2; 
  result = (MulInd *)VariableSet_ComputeMargInd(arg1,arg2);
  *(MulInd **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BNet_1ComputeSumMarginals(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  BNet *arg1 = (BNet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BNet **)&jarg1; 
  BNet_ComputeSumMarginals(arg1);
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BNet_1Create_1List(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  VariableOrdering *arg1 = (VariableOrdering *) 0 ;
  List *arg2 = (List *) 0 ;
  BNet *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VariableOrdering **)&jarg1; 
  arg2 = *(List **)&jarg2; 
  result = (BNet *)BNet_Create_List(arg1,arg2);
  *(BNet **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BNet_1Create_1List2(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VariableOrdering *arg1 = (VariableOrdering *) 0 ;
  List *arg2 = (List *) 0 ;
  List *arg3 = (List *) 0 ;
  BNet *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VariableOrdering **)&jarg1; 
  arg2 = *(List **)&jarg2; 
  arg3 = *(List **)&jarg3; 
  result = (BNet *)BNet_Create_List2(arg1,arg2,arg3);
  *(BNet **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BNet_1InitializePotentialsLog(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  BNet *arg1 = (BNet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BNet **)&jarg1; 
  BNet_InitializePotentialsLog(arg1);
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BNet_1CollectEvidenceLog(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  BNet *arg1 = (BNet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BNet **)&jarg1; 
  BNet_CollectEvidenceLog(arg1);
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BNet_1DistributeEvidenceLog(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  BNet *arg1 = (BNet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BNet **)&jarg1; 
  BNet_DistributeEvidenceLog(arg1);
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_BuildSimpleBNetDObsLog(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  BNet *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (BNet *)BuildSimpleBNetDObsLog(arg1);
  *(BNet **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Print_1BNetLog(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  BNet *arg1 = (BNet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BNet **)&jarg1; 
  Print_BNetLog(arg1);
}


SWIGEXPORT jstring JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Pot_1ToStringLog(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  Pot *arg1 = (Pot *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Pot **)&jarg1; 
  result = (char *)Pot_ToStringLog(arg1);
  if(result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Observation_1CreateLog(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  VariableSet *arg1 = (VariableSet *) 0 ;
  int arg2 ;
  Observation *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VariableSet **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (Observation *)Observation_CreateLog(arg1,arg2);
  *(Observation **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Pot_1CreateTabularUnityLog(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  VariableSet *arg2 = (VariableSet *) 0 ;
  Pot *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(VariableSet **)&jarg2; 
  result = (Pot *)Pot_CreateTabularUnityLog(arg1,arg2);
  *(Pot **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Pot_1ProductTabularLog(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  Pot *arg1 = (Pot *) 0 ;
  Pot *arg2 = (Pot *) 0 ;
  MulInd *arg3 = (MulInd *) 0 ;
  Pot *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Pot **)&jarg1; 
  arg2 = *(Pot **)&jarg2; 
  arg3 = *(MulInd **)&jarg3; 
  result = (Pot *)Pot_ProductTabularLog(arg1,arg2,arg3);
  *(Pot **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Pot_1UpdateRatioTabularLog(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  Pot *arg1 = (Pot *) 0 ;
  Pot *arg2 = (Pot *) 0 ;
  Pot *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Pot **)&jarg1; 
  arg2 = *(Pot **)&jarg2; 
  result = (Pot *)Pot_UpdateRatioTabularLog(arg1,arg2);
  *(Pot **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Pot_1SumMarginTabularLog(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  Pot *arg1 = (Pot *) 0 ;
  MulInd *arg2 = (MulInd *) 0 ;
  Pot *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Pot **)&jarg1; 
  arg2 = *(MulInd **)&jarg2; 
  result = (Pot *)Pot_SumMarginTabularLog(arg1,arg2);
  *(Pot **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Pot_1SumMarginTabularSingleVblLog(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  Pot *arg1 = (Pot *) 0 ;
  Variable *arg2 = (Variable *) 0 ;
  Pot *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Pot **)&jarg1; 
  arg2 = *(Variable **)&jarg2; 
  result = (Pot *)Pot_SumMarginTabularSingleVblLog(arg1,arg2);
  *(Pot **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_umb_junctionbox_junctionboxJNI_Print_1BNet(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  BNet *arg1 = (BNet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BNet **)&jarg1; 
  Print_BNet(arg1);
}


#ifdef __cplusplus
}
#endif

